/**
 * player.js
 * Builds the "player" object that lives inside Game.state.player.
 * This is the only factory that creates the user's player; NPCs
 * generated by the world AI (Phase 9) will use their own factory in
 * /js/database, reusing Game.player.attributes.
 */
(function (Game) {
  function createPlayer({ firstName, lastName, countryCode, stateCode, hand, position, archetypeId, potentialTier }) {
    const attributes = archetypeId
      ? Game.player.attributes.generateInitialAttributesForArchetype(position, archetypeId)
      : Game.player.attributes.generateInitialAttributes(position);
    const potential = potentialTier
      ? Game.player.attributes.generatePotentialForTier(potentialTier)
      : Game.player.attributes.generatePotential();
    const attributeCaps = Game.player.attributes.generateAttributeCaps(attributes, potential);
    const scouting = Game.player.attributes.scoutProjection(potential);
    const archetype = archetypeId
      ? Game.player.attributes.archetypeLabel(position, archetypeId)
      : Game.player.attributes.deriveArchetype(position, attributes);

    const isEuropean = Game.leagues && Game.leagues.leagueData && Game.leagues.leagueData.isEuropean
      ? Game.leagues.leagueData.isEuropean(countryCode)
      : false;

    return {
      id: Game.utils.uid('player'),
      firstName,
      lastName,
      countryCode,
      stateCode: stateCode || null,
      hand,
      position,
      age: Game.CONFIG.CAREER.START_AGE,
      archetype,
      academy: isEuropean && Game.data && Game.data.europeanAcademies && Game.data.europeanAcademies.getAcademy
        ? Game.data.europeanAcademies.getAcademy(countryCode)
        : null,

      attributes,
      potential, // hidden: never shown directly in the UI
      attributeCaps, // hidden: individual ceiling per attribute (Phase 4)
      scouting, // { grade, label } — what the user actually sees

      // Filled in during later phases:
      team: null,
      league: null,
      contract: null,
      finances: { balance: 0, sponsorships: [], expenses: [] },
      popularity: { local: 5, national: 0, global: 0 },
      relationships: { coach: 50, teammates: 50, agent: 50, family: 70, press: 50, fans: 50 },
      careerTotals: {
        games: 0,
        goals: 0,
        assists: 0,
        points: 0,
        plusMinus: 0,
        penaltyMinutes: 0,
        shots: 0,
        hits: 0,
        blocksMade: 0,
        faceoffsWon: 0,
        faceoffsTaken: 0,
        wins: 0,
        savesMade: 0,
        shotsFaced: 0,
        goalsAgainst: 0,
        shutouts: 0,
      },
      awards: [],
      injuries: [],
    };
  }

  Game.player = Game.player || {};
  Game.player.createPlayer = createPlayer;
})(window.Game = window.Game || {});
